config/routes.rb
Rails.application.routes.draw do
  
  resources :video_tags
  root 'welcome#index'
  get 'welcome/index'

  resources :tags
  resources :socials
  resources :arts
  resources :roles
  resources :users
  resources :speedpaints
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/speedpaint.rb
class Speedpaint < ApplicationRecord
  belongs_to :video_tag
end

app/controllers/speedpaints_controller.rb
class SpeedpaintsController < ApplicationController
  before_filter :auth_redirect, only: [:new, :edit]
  before_action :set_speedpaint, only: [:show, :edit, :update, :destroy]
  
  # GET /speedpaints
  # GET /speedpaints.json
  def index
    @speedpaints = Speedpaint.all
  end

  # GET /speedpaints/1
  # GET /speedpaints/1.json
  def show
  end

  # GET /speedpaints/new
  def new
    @speedpaint = Speedpaint.new
  end

  # GET /speedpaints/1/edit
  def edit
  end

  # POST /speedpaints
  # POST /speedpaints.json
  def create
    @speedpaint = Speedpaint.new(speedpaint_params)

    respond_to do |format|
      if @speedpaint.save
        format.html { redirect_to @speedpaint, notice: 'Speedpaint was successfully created.' }
        format.json { render :show, status: :created, location: @speedpaint }
      else
        format.html { render :new }
        format.json { render json: @speedpaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /speedpaints/1
  # PATCH/PUT /speedpaints/1.json
  def update
    respond_to do |format|
      if @speedpaint.update(speedpaint_params)
        format.html { redirect_to @speedpaint, notice: 'Speedpaint was successfully updated.' }
        format.json { render :show, status: :ok, location: @speedpaint }
      else
        format.html { render :edit }
        format.json { render json: @speedpaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /speedpaints/1
  # DELETE /speedpaints/1.json
  def destroy
    @speedpaint.destroy
    respond_to do |format|
      format.html { redirect_to speedpaints_url, notice: 'Speedpaint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_speedpaint
      @speedpaint = Speedpaint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def speedpaint_params
      params.require(:speedpaint).permit(:name, :description, :url, :creation_date, :video_tag_id)
    end
end

app/helpers/speedpaints_helper.rb
module SpeedpaintsHelper
  
  # this method will embed the code from the partial
  def youtube_video_index(url)
    if defined?(url) && (url !='') then
      url_edited = url.sub!("watch?v=", "embed/");
      render :partial => 'video_index', :locals => { :url => url_edited }
    end
  end 

  def youtube_video(url)
    if defined?(url) && (url !='') then
      url_edited = url.sub!("watch?v=", "v/");
      render :partial => 'video', :locals => { :url => url_edited }
    end
  end 
  
end

app/views/speedpaints/_form.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12  col-sm-10 col-md-6 col-lg-6 col-sm-offset-1 col-md-offset-3 col-lg-offset-3">

			<%= form_for(speedpaint) do |f| %>
			<% if speedpaint.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(speedpaint.errors.count, "error") %> prohibited this speedpaint from being saved:</h2>

				<ul>
					<% speedpaint.errors.full_messages.each do |message| %>
					<li><%= message %></li>
					<% end %>
				</ul>
			</div>
			<% end %>
	
			<div class="form-group">
				<%= f.label :video_url %>
				<%= f.text_field :url, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= f.label :name %>
				<%= f.text_field :name, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= f.label :description %>
				<%= f.text_area :description, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= f.label :video_tag %>
				<%= f.collection_select :video_tag_id, VideoTag.all, :id, :name, {:prompt => "Please Select Video Tag"}, {:class => "form-control"} %>
			</div>

			<div class="form-group">
				<%= f.label :creation_date %>
				<%= f.date_select :creation_date, { :discard_day => true}, class: "form-control" %>
			</div>

			<div class="actions">
				<%= button_tag(type: 'submit', class: "btn btn-primary") do %>
				<i class="fa fa-floppy-o" aria-hidden="true"></i> Save
				<% end %>
				<%= link_to '<i class="fa fa-floppy-o" aria-hidden="true"></i> Cancel'.html_safe, speedpaints_path, {class: "btn btn-danger"} %>
			</div>

			<% end %>
		</div>
	</div>
</div>

app/views/speedpaints/_video.html.erb
<iframe width="100%" height="600" src="<%= url %>" frameborder="0" allowfullscreen="allowfullscreen"></iframe>

app/views/speedpaints/_video_index.html.erb
<iframe type="text/html" width="100%" height="275" src="<%= url %>" frameborder="0" allowfullscreen></iframe>

app/views/speedpaints/edit.html.erb
<% provide(:title, @speedpaint.name) %>
<% provide(:phrase, "Edit") %>

<%= render 'form', speedpaint: @speedpaint %>

app/views/speedpaints/index.html.erb
<% provide(:title, "Speedpaints") %>
<% provide(:phrase, "digital art in motion") %>

<p id="notice"><%= notice %></p>

<!-- Start margin -->
<div class="margin-collection">
             
		<!-- Start projects -->
		<div class="container">

			<ul class="portfolio-filter text-center">
				<li><a class="btn btn-default active" href="#" data-filter="*">All Collection</a></li>
				<% VideoTag.all.each do |video_tag| %>
				<li><a class="btn btn-default" href="#" data-filter=".<%= video_tag.id %>"><%= video_tag.name %></a></li>
				<% end %>
			<% if logged_in? && current_user.role_id == 1 %> 
			<%= link_to 'Manage Tags', video_tags_path, {class: "btn btn-info"} %>
			<% end %>
			</ul><!--/#portfolio-filter-->

		<% if logged_in? && current_user.role_id == 1 %> 
		<div class="row text-center">
			<%= link_to '<i class="fa fa-plus" aria-hidden="true"></i> Add New Speedpaint'.html_safe, new_speedpaint_path, {class: "btn btn-success"} %>
		</div>
		<% end %>

			<div class="row">
				<div class="portfolio-items">
					<% @speedpaints.each do |speedpaint| %>
					<div class="portfolio-item <%= speedpaint.video_tag_id %> col-xs-12 col-sm-4 col-md-4 text-center">
						<div class="recent-work-wrap text-center">
							<%= youtube_video_index speedpaint.url %>
						</div>
						<% if logged_in? && current_user.role_id == 1 %> 
							<%= link_to 'View', speedpaint, {class: "btn btn-primary"} %>
						<% end %>
					</div><!-- /portfolio-item -->
					<% end %>
				</div><!-- /portfolio-items -->
			</div><!-- /row -->
               
		</div><!-- /container -->
       
	</div>
	<!-- End margin -->

app/views/speedpaints/new.html.erb
<% provide(:title, "New Speedpaint") %>
<% provide(:phrase, "add new speedpaint to your collection") %>

<%= render 'form', speedpaint: @speedpaint %>

app/views/speedpaints/show.html.erb
<% provide(:title, @speedpaint.name) %>
<% provide(:phrase, @speedpaint.description) %>
<%= link_to '<i class="fa fa-arrow-left" aria-hidden="true"></i> Back to all collections'.html_safe, speedpaints_path, class: "btn btn-default", method: :get %>

<% if logged_in? && current_user.role_id == 1 %> 
<%= link_to '<i class="fa fa-edit" aria-hidden="true"></i> Edit'.html_safe, edit_speedpaint_path(@speedpaint), {class: "btn btn-primary"} %>
<%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i> Delete'.html_safe, @speedpaint, class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure you want to delete " + @speedpaint.name + " speedpaint?" } %>
<% end %>

<p>
  <strong>Creation date:</strong>
  <%= @speedpaint.creation_date %>
</p>

<p>
  <%= youtube_video @speedpaint.url %>
</p>