config/routes.rb
Rails.application.routes.draw do
  
  resources :video_tags
  root 'welcome#index'
  get 'welcome/index'

  resources :tags
  resources :socials
  resources :arts
  resources :roles
  resources :users
  resources :speedpaints
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/art.rb
class Art < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :tag
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  before_filter :auth_redirect, only: [:new, :edit]
  before_action :set_art, only: [:show, :edit, :update, :destroy]

  # GET /arts
  # GET /arts.json
  def index
    @arts = Art.all
  end

  # GET /arts/1
  # GET /arts/1.json
  def show
  end

  # GET /arts/new
  def new
    @art = Art.new
  end

  # GET /arts/1/edit
  def edit
  end

  # POST /arts
  # POST /arts.json
  def create
    @art = Art.new(art_params)

    respond_to do |format|
      if @art.save
        format.html { redirect_to @art }
        format.json { render :show, status: :created, location: @art }
        flash[:success] = "Art was successfully created!"
      else
        format.html { render :new }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arts/1
  # PATCH/PUT /arts/1.json
  def update
    respond_to do |format|
      if @art.update(art_params)
        format.html { redirect_to @art, notice: 'Art was successfully updated.' }
        format.json { render :show, status: :ok, location: @art }
      else
        format.html { render :edit }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arts/1
  # DELETE /arts/1.json
  def destroy
    @art.destroy
    respond_to do |format|
      format.html { redirect_to arts_url, notice: 'Art was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_art
      @art = Art.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def art_params
      # params.fetch(:art, :name, :description, :creation_date, :image, {})
      params.require(:art).permit(:name, :description, :creation_date, :image, :tag_id)
    end
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/views/arts/_form.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12  col-sm-10 col-md-6 col-lg-6 col-sm-offset-1 col-md-offset-3 col-lg-offset-3">

<%= form_for @art, :html => {:multipart => true} do |f| %>
  <% if art.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(art.errors.count, "error") %> prohibited this art from being saved:</h2>

      <ul>
      <% art.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	
			<div class="form-group">
    <%= f.label :picture %>
    <%= f.file_field :image, class: "form-control" %>
			</div>

			<div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
			</div>

			<div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= f.label :tag %>
				<%= f.collection_select :tag_id, Tag.all, :id, :name, {:prompt => "Please Select Tag"}, {:class => "form-control"} %>
			</div>

			<div class="form-group">
    <%= f.label :creation_date %>
    <%= f.date_select :creation_date, { :discard_day => true}, class: "form-control" %>
			</div>

			<div class="actions">
				<%= button_tag(type: 'submit', class: "btn btn-primary") do %>
					<i class="fa fa-floppy-o" aria-hidden="true"></i> Save
				<% end %>
				<%= link_to '<i class="fa fa-floppy-o" aria-hidden="true"></i> Cancel'.html_safe, arts_path, {class: "btn btn-danger"} %>
			</div>
<% end %>
		</div>
	</div>
</div>

app/views/arts/edit.html.erb
<% provide(:title, @art.name) %>
<% provide(:phrase, "Edit") %>

<%= render 'form', art: @art %>

app/views/arts/index.html.erb
<% provide(:title, "Art Works") %>
<% provide(:phrase, "drawings and paints") %>

<!-- Start margin -->
<div class="margin-collection">
             
	<!-- Start projects -->
	<div class="container">

		<ul class="portfolio-filter text-center">
			<li><a class="btn btn-default active" href="#" data-filter="*">All Collection</a></li>
			<% Tag.all.each do |tag| %>
			<li><a class="btn btn-default" href="#" data-filter=".<%= tag.id %>"><%= tag.name %></a></li>
			<% end %>
			<% if logged_in? && current_user.role_id == 1 %> 
			<%= link_to 'Manage Tags', tags_path, {class: "btn btn-info"} %>
			<% end %>
		</ul><!--/#portfolio-filter-->

		<% if logged_in? && current_user.role_id == 1 %> 
		<div class="row text-center">
			<%= link_to '<i class="fa fa-plus" aria-hidden="true"></i> Add New Art'.html_safe, new_art_path, {class: "btn btn-success"} %>
		</div>
		<% end %>

		<div class="row">
			<div class="portfolio-items">
				<% @arts.each do |art| %>
				<div class="portfolio-item <%= art.tag_id %> col-xs-12 col-sm-4 col-md-4">
					<div class="recent-work-wrap text-center">
						<%= image_tag art.image_url %>
						<div class="overlay">
							<div class="recent-work-inner">
								<p class="art-name"><%= art.name %></p>
								<p class="art-description"><%= art.description %></p>
								<%= link_to 'View Art', art, {class: "btn btn-default"} %>
							</div> 
						</div>
					</div>
				</div><!-- /portfolio-item -->
				<% end %>
			</div><!-- /portfolio-items -->
		</div><!-- /row -->
               
	</div><!-- /container -->
       
</div>
<!-- End margin -->

app/views/arts/new.html.erb
<% provide(:title, "New Art") %>
<% provide(:phrase, "add new art to your collection") %>

<%= render 'form', art: @art %>

app/views/arts/show.html.erb
<% provide(:title, @art.name) %>
<% provide(:phrase, @art.description) %>
<%= link_to '<i class="fa fa-arrow-left" aria-hidden="true"></i> Back to all collections'.html_safe, arts_path, class: "btn btn-default", method: :get %>

<% if logged_in? && current_user.role_id == 1 %> 
<%= link_to '<i class="fa fa-edit" aria-hidden="true"></i> Edit'.html_safe, edit_art_path(@art), {class: "btn btn-primary"} %>
<%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i> Delete'.html_safe, @art, class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure you want to delete " + @art.name + " art?" } %>
<% end %>

<p>
	<strong>Created:</strong>
	<%= @art.creation_date %>
</p>

<p>
	<%= image_tag @art.image_url.to_s %>
</p>